permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

title : Jeremy Marc
tagline: Software Ingineer
author :
  name : Jeremy Marc
  email : jeremy.marc@me.com
  github : jeremymarc
  twitter : jeremymarc
production_url : http://jeremymarc.github.com

markdown: redcarpet
redcarpet:
    #extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

JB :
  version : 0.2.13
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  comments :
    provider : false
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-36427103-1'
  sharing :
    provider : false
